### ISSUE TITLE
Add to Packagist.org

### ISSUE THREAD

**Issue by peterjaap** [kiwicommerce/magento2-customer-password#6]
It's not available on Packagist.org;

![image](https://user-images.githubusercontent.com/431360/69045474-32148880-09f7-11ea-8557-acbd71aab730.png)

**Comment by kiwi-commerce** [comment]
Hi @peterjaap ,

Thank you for reminding.
We will add this extension to the Packagist.org soon.

Thank you.

**Comment by kiwi-commerce** [comment]
Hello @peterjaap ,

We have published the package into Packagist.org.

- https://packagist.org/packages/kiwicommerce/module-customer-password

So now, anyone can install this package using the composer.
`composer require kiwicommerce/module-customer-password`

Thank you.
