### ISSUE TITLE
not work with 2.3.3

### ISSUE THREAD

**Issue by benyang2015** [kiwicommerce/magento2-customer-password#9]
Class argument is invalid: Magento\\Framework\\View\\Element\\UiComponent\\Context

**Comment by gihovani** [comment]
> Class argument is invalid: Magento\Framework\View\Element\UiComponent\Context

 in view/adminhtml/ui_component/kiwicommerce_customerpassword_passwordlog_index.xml remove or comment this lines:

**Comment by gihovani** [comment]
> Class argument is invalid: Magento\Framework\View\Element\UiComponent\Context

#10 this pr fix this bug

**Comment by kiwi-commerce** [comment]
Hello,

Thank you for your report.
We have merged changes of PR #10 and it will be released on the next upcoming version.

Thank you.
